version: "3.6"

services:
 minetest:
  build: dev
  volumes:
   - "world_data:/root/.minetest/worlds/world"
  ports:
   - "30000:30000/udp"
  command: ["/usr/local/bin/minetestserver", "--config", "/etc/minetest/minetest.conf", "--gameid", "nodecore", "--verbose", "--world", "/root/.minetest/worlds/world/"]

volumes:
  world_data: {}
