version: "3.6"

services:
 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.3.0
  user: root
  volumes:
   - "world_data:/root/.minetest/worlds/world"
  ports:
   - "30000:30000/udp"

volumes:
  world_data: {}
